import pytest

provider_1003000126 = {
    "National Provider Identifier": 1003000126,
    "Last Name/Organization Name of the Provider": "ENKESHAFI",
    "First Name of the Provider": "ARDALAN",
    "Middle Initial of the Provider": "",
    "Credentials of the Provider": "M.D.",
    "Gender of the Provider": "M",
    "Entity Type of the Provider": "I",
    "Street Address 1 of the Provider": "900 SETON DR",
    "Street Address 2 of the Provider": "",
    "City of the Provider": "CUMBERLAND",
    "Zip Code of the Provider": "215021854",
    "State Code of the Provider": "MD",
    "Country Code of the Provider": "US",
    "Provider Type": "Internal Medicine",
    "medicaredata": [
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99217",
            "hcpcs_description": "Hospital observation care discharge",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 100,
            "number_of_medicare_beneficiaries": 96,
            "number_of_distinct_medicare_beneficiary_per_day_services": 100,
            "average_Medicare_allowed_amount": 73.3988,
            "average_submitted_charge_amount": 325.78,
            "average_medicare_payment_amount": 56.8272,
            "average_medicare_standardized_amount": 57.4924
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99218",
            "hcpcs_description": "Hospital observation care typically 30 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 26,
            "number_of_medicare_beneficiaries": 25,
            "number_of_distinct_medicare_beneficiary_per_day_services": 26,
            "average_Medicare_allowed_amount": 100.08,
            "average_submitted_charge_amount": 449,
            "average_medicare_payment_amount": 78.46,
            "average_medicare_standardized_amount": 79.306153846
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99219",
            "hcpcs_description": "Hospital observation care typically 50 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 52,
            "number_of_medicare_beneficiaries": 51,
            "number_of_distinct_medicare_beneficiary_per_day_services": 52,
            "average_Medicare_allowed_amount": 136.38,
            "average_submitted_charge_amount": 614,
            "average_medicare_payment_amount": 102.80769231,
            "average_medicare_standardized_amount": 103.89538462
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99220",
            "hcpcs_description": "Hospital observation care typically 70 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 59,
            "number_of_medicare_beneficiaries": 59,
            "number_of_distinct_medicare_beneficiary_per_day_services": 59,
            "average_Medicare_allowed_amount": 190.36372881,
            "average_submitted_charge_amount": 755.93220339,
            "average_medicare_payment_amount": 141.29355932,
            "average_medicare_standardized_amount": 142.86576271
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99221",
            "hcpcs_description": "Initial hospital inpatient care, typically 30 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 16,
            "number_of_medicare_beneficiaries": 16,
            "number_of_distinct_medicare_beneficiary_per_day_services": 16,
            "average_Medicare_allowed_amount": 101.68,
            "average_submitted_charge_amount": 462.8125,
            "average_medicare_payment_amount": 79.71,
            "average_medicare_standardized_amount": 80.75
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99222",
            "hcpcs_description": "Initial hospital inpatient care, typically 50 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 59,
            "number_of_medicare_beneficiaries": 57,
            "number_of_distinct_medicare_beneficiary_per_day_services": 59,
            "average_Medicare_allowed_amount": 137.31,
            "average_submitted_charge_amount": 625,
            "average_medicare_payment_amount": 105.82542373,
            "average_medicare_standardized_amount": 107.07067797
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99223",
            "hcpcs_description": "Initial hospital inpatient care, typically 70 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 114,
            "number_of_medicare_beneficiaries": 110,
            "number_of_distinct_medicare_beneficiary_per_day_services": 114,
            "average_Medicare_allowed_amount": 206.06157895,
            "average_submitted_charge_amount": 923.99122807,
            "average_medicare_payment_amount": 160.37719298,
            "average_medicare_standardized_amount": 160.02631579
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99232",
            "hcpcs_description": "Subsequent hospital inpatient care, typically 25 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 627,
            "number_of_medicare_beneficiaries": 233,
            "number_of_distinct_medicare_beneficiary_per_day_services": 627,
            "average_Medicare_allowed_amount": 72.62245614,
            "average_submitted_charge_amount": 326.24561404,
            "average_medicare_payment_amount": 56.366730463,
            "average_medicare_standardized_amount": 57.047894737
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99233",
            "hcpcs_description": "Subsequent hospital inpatient care, typically 35 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 207,
            "number_of_medicare_beneficiaries": 127,
            "number_of_distinct_medicare_beneficiary_per_day_services": 207,
            "average_Medicare_allowed_amount": 106.65391304,
            "average_submitted_charge_amount": 461.07246377,
            "average_medicare_payment_amount": 82.820676329,
            "average_medicare_standardized_amount": 83.196038647
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99239",
            "hcpcs_description": "Hospital discharge day management, more than 30 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 341,
            "number_of_medicare_beneficiaries": 291,
            "number_of_distinct_medicare_beneficiary_per_day_services": 341,
            "average_Medicare_allowed_amount": 108.36328446,
            "average_submitted_charge_amount": 481.68621701,
            "average_medicare_payment_amount": 84.056158358,
            "average_medicare_standardized_amount": 84.955131965
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99291",
            "hcpcs_description": "Critical care delivery critically ill or injured patient, first 30-74 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 36,
            "number_of_medicare_beneficiaries": 23,
            "number_of_distinct_medicare_beneficiary_per_day_services": 36,
            "average_Medicare_allowed_amount": 224.17,
            "average_submitted_charge_amount": 1400,
            "average_medicare_payment_amount": 175.75,
            "average_medicare_standardized_amount": 177.65666667
        }
    ]
}

provider_1003000407 = {
    "National Provider Identifier": 1003000407,
    "Last Name/Organization Name of the Provider": "GIRARDI",
    "First Name of the Provider": "DAVID",
    "Middle Initial of the Provider": "J",
    "Credentials of the Provider": "D.O.",
    "Gender of the Provider": "M",
    "Entity Type of the Provider": "I",
    "Street Address 1 of the Provider": "100 HOSPITAL RD",
    "Street Address 2 of the Provider": "",
    "City of the Provider": "BROOKVILLE",
    "Zip Code of the Provider": "158251367",
    "State Code of the Provider": "PA",
    "Country Code of the Provider": "US",
    "Provider Type": "Family Practice",
    "medicaredata": [
        {
                            "medicare_participation_indicator": "Y",
                            "hcpcs_code": "99217",
                            "hcpcs_description": "Hospital observation care discharge",
                            "hcpcs_drug_indicator": "N",
                            "number_of_services": 15,
                            "number_of_medicare_beneficiaries": 15,
                            "number_of_distinct_medicare_beneficiary_per_day_services": 15,
                            "average_Medicare_allowed_amount": 72.3,
                            "average_submitted_charge_amount": 102.33333333,
                            "average_medicare_payment_amount": 54.42,
                            "average_medicare_standardized_amount": 57.96
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99219",
            "hcpcs_description": "Hospital observation care typically 50 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 27,
            "number_of_medicare_beneficiaries": 26,
            "number_of_distinct_medicare_beneficiary_per_day_services": 27,
            "average_Medicare_allowed_amount": 135.33,
            "average_submitted_charge_amount": 170,
            "average_medicare_payment_amount": 101.85,
            "average_medicare_standardized_amount": 107.81074074
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99220",
            "hcpcs_description": "Hospital observation care typically 70 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 34,
            "number_of_medicare_beneficiaries": 34,
            "number_of_distinct_medicare_beneficiary_per_day_services": 34,
            "average_Medicare_allowed_amount": 185.02,
            "average_submitted_charge_amount": 213.67647059,
            "average_medicare_payment_amount": 139.26,
            "average_medicare_standardized_amount": 147.72
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99221",
            "hcpcs_description": "Initial hospital inpatient care, typically 30 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 19,
            "number_of_medicare_beneficiaries": 19,
            "number_of_distinct_medicare_beneficiary_per_day_services": 19,
            "average_Medicare_allowed_amount": 101.24,
            "average_submitted_charge_amount": 125,
            "average_medicare_payment_amount": 73.383157895,
            "average_medicare_standardized_amount": 81.812631579
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99222",
            "hcpcs_description": "Initial hospital inpatient care, typically 50 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 39,
            "number_of_medicare_beneficiaries": 37,
            "number_of_distinct_medicare_beneficiary_per_day_services": 39,
            "average_Medicare_allowed_amount": 136.44,
            "average_submitted_charge_amount": 166.92307692,
            "average_medicare_payment_amount": 100.04717949,
            "average_medicare_standardized_amount": 106.00025641
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99223",
            "hcpcs_description": "Initial hospital inpatient care, typically 70 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 74,
            "number_of_medicare_beneficiaries": 73,
            "number_of_distinct_medicare_beneficiary_per_day_services": 74,
            "average_Medicare_allowed_amount": 200.545,
            "average_submitted_charge_amount": 243.39189189,
            "average_medicare_payment_amount": 149.435,
            "average_medicare_standardized_amount": 161.39081081
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99226",
            "hcpcs_description": "Subsequent observation care, typically 35 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 17,
            "number_of_medicare_beneficiaries": 13,
            "number_of_distinct_medicare_beneficiary_per_day_services": 17,
            "average_Medicare_allowed_amount": 100.36705882,
            "average_submitted_charge_amount": 131.17647059,
            "average_medicare_payment_amount": 75.539411765,
            "average_medicare_standardized_amount": 83.570588235
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99231",
            "hcpcs_description": "Subsequent hospital inpatient care, typically 15 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 74,
            "number_of_medicare_beneficiaries": 48,
            "number_of_distinct_medicare_beneficiary_per_day_services": 74,
            "average_Medicare_allowed_amount": 39.16,
            "average_submitted_charge_amount": 90,
            "average_medicare_payment_amount": 27.841081081,
            "average_medicare_standardized_amount": 30.649459459
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99232",
            "hcpcs_description": "Subsequent hospital inpatient care, typically 25 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 241,
            "number_of_medicare_beneficiaries": 122,
            "number_of_distinct_medicare_beneficiary_per_day_services": 241,
            "average_Medicare_allowed_amount": 71.9,
            "average_submitted_charge_amount": 150,
            "average_medicare_payment_amount": 53.631327801,
            "average_medicare_standardized_amount": 57.323858921
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99233",
            "hcpcs_description": "Subsequent hospital inpatient care, typically 35 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 76,
            "number_of_medicare_beneficiaries": 48,
            "number_of_distinct_medicare_beneficiary_per_day_services": 76,
            "average_Medicare_allowed_amount": 103.97,
            "average_submitted_charge_amount": 175,
            "average_medicare_payment_amount": 78.25,
            "average_medicare_standardized_amount": 82.884736842
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99239",
            "hcpcs_description": "Hospital discharge day management, more than 30 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 129,
            "number_of_medicare_beneficiaries": 123,
            "number_of_distinct_medicare_beneficiary_per_day_services": 129,
            "average_Medicare_allowed_amount": 106.69,
            "average_submitted_charge_amount": 135.94573643,
            "average_medicare_payment_amount": 79.241860465,
            "average_medicare_standardized_amount": 84.979689922
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99306",
            "hcpcs_description": "Initial nursing facility visit, typically 45 minutes per day",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 11,
            "number_of_medicare_beneficiaries": 11,
            "number_of_distinct_medicare_beneficiary_per_day_services": 11,
            "average_Medicare_allowed_amount": 165.59,
            "average_submitted_charge_amount": 185,
            "average_medicare_payment_amount": 124.63,
            "average_medicare_standardized_amount": 124.63
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99316",
            "hcpcs_description": "Nursing facility discharge management, more than 30 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 39,
            "number_of_medicare_beneficiaries": 38,
            "number_of_distinct_medicare_beneficiary_per_day_services": 39,
            "average_Medicare_allowed_amount": 105.05,
            "average_submitted_charge_amount": 120,
            "average_medicare_payment_amount": 79.07,
            "average_medicare_standardized_amount": 84.13
        }
    ]
}

provider_1003000142 = {
    "National Provider Identifier": 1003000142,
    "Last Name/Organization Name of the Provider": "KHALIL",
    "First Name of the Provider": "RASHID",
    "Middle Initial of the Provider": "",
    "Credentials of the Provider": "M.D.",
    "Gender of the Provider": "M",
    "Entity Type of the Provider": "I",
    "Street Address 1 of the Provider": "4126 N HOLLAND SYLVANIA RD",
    "Street Address 2 of the Provider": "SUITE 220",
    "City of the Provider": "TOLEDO",
    "Zip Code of the Provider": "436233536",
    "State Code of the Provider": "OH",
    "Country Code of the Provider": "US",
    "Provider Type": "Anesthesiology",
    "medicaredata": [
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "20611",
            "hcpcs_description": "Aspiration and/or injection of major joint or joint capsule with recording and reporting using ultrasound guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 35,
            "number_of_medicare_beneficiaries": 21,
            "number_of_distinct_medicare_beneficiary_per_day_services": 34,
            "average_Medicare_allowed_amount": 73.095142857,
            "average_submitted_charge_amount": 142.8,
            "average_medicare_payment_amount": 53.834285714,
            "average_medicare_standardized_amount": 55.245714286
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "62323",
            "hcpcs_description": "Injection of substance into spinal canal of lower back or sacrum using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 40,
            "number_of_medicare_beneficiaries": 32,
            "number_of_distinct_medicare_beneficiary_per_day_services": 40,
            "average_Medicare_allowed_amount": 101.09,
            "average_submitted_charge_amount": 159,
            "average_medicare_payment_amount": 79.25,
            "average_medicare_standardized_amount": 81.31
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "63650",
            "hcpcs_description": "Implantation of spinal neurostimulator electrodes, accessed through the skin",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 33,
            "number_of_medicare_beneficiaries": 13,
            "number_of_distinct_medicare_beneficiary_per_day_services": 17,
            "average_Medicare_allowed_amount": 312.45454545,
            "average_submitted_charge_amount": 707,
            "average_medicare_payment_amount": 243.68484848,
            "average_medicare_standardized_amount": 195.24484848
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64483",
            "hcpcs_description": "Injections of anesthetic and/or steroid drug into lower or sacral spine nerve root using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 61,
            "number_of_medicare_beneficiaries": 48,
            "number_of_distinct_medicare_beneficiary_per_day_services": 61,
            "average_Medicare_allowed_amount": 135.60196721,
            "average_submitted_charge_amount": 392.21311475,
            "average_medicare_payment_amount": 102.81114754,
            "average_medicare_standardized_amount": 106.00196721
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64484",
            "hcpcs_description": "Injections of anesthetic and/or steroid drug into lower or sacral spine nerve root using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 31,
            "number_of_medicare_beneficiaries": 25,
            "number_of_distinct_medicare_beneficiary_per_day_services": 31,
            "average_Medicare_allowed_amount": 53.102903226,
            "average_submitted_charge_amount": 139.35483871,
            "average_medicare_payment_amount": 41.630967742,
            "average_medicare_standardized_amount": 42.606129032
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64490",
            "hcpcs_description": "Injections of upper or middle spine facet joint using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 22,
            "number_of_medicare_beneficiaries": 14,
            "number_of_distinct_medicare_beneficiary_per_day_services": 22,
            "average_Medicare_allowed_amount": 113.55909091,
            "average_submitted_charge_amount": 202.27272727,
            "average_medicare_payment_amount": 89.033636364,
            "average_medicare_standardized_amount": 91.671363636
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64491",
            "hcpcs_description": "Injections of upper or middle spine facet joint using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 22,
            "number_of_medicare_beneficiaries": 14,
            "number_of_distinct_medicare_beneficiary_per_day_services": 22,
            "average_Medicare_allowed_amount": 64.838636364,
            "average_submitted_charge_amount": 112.5,
            "average_medicare_payment_amount": 50.834090909,
            "average_medicare_standardized_amount": 51.989090909
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64492",
            "hcpcs_description": "Injections of upper or middle spine facet joint using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 22,
            "number_of_medicare_beneficiaries": 14,
            "number_of_distinct_medicare_beneficiary_per_day_services": 22,
            "average_Medicare_allowed_amount": 65.543636364,
            "average_submitted_charge_amount": 113.63636364,
            "average_medicare_payment_amount": 51.389545455,
            "average_medicare_standardized_amount": 52.597272727
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64493",
            "hcpcs_description": "Injections of lower or sacral spine facet joint using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 25,
            "number_of_medicare_beneficiaries": 16,
            "number_of_distinct_medicare_beneficiary_per_day_services": 25,
            "average_Medicare_allowed_amount": 135.77,
            "average_submitted_charge_amount": 302,
            "average_medicare_payment_amount": 106.45,
            "average_medicare_standardized_amount": 109.74
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64494",
            "hcpcs_description": "Injections of lower or sacral spine facet joint using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 25,
            "number_of_medicare_beneficiaries": 16,
            "number_of_distinct_medicare_beneficiary_per_day_services": 25,
            "average_Medicare_allowed_amount": 78.44,
            "average_submitted_charge_amount": 168,
            "average_medicare_payment_amount": 61.49,
            "average_medicare_standardized_amount": 62.89
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64495",
            "hcpcs_description": "Injections of lower or sacral spine facet joint using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 25,
            "number_of_medicare_beneficiaries": 16,
            "number_of_distinct_medicare_beneficiary_per_day_services": 25,
            "average_Medicare_allowed_amount": 79.43,
            "average_submitted_charge_amount": 172,
            "average_medicare_payment_amount": 62.27,
            "average_medicare_standardized_amount": 63.73
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64635",
            "hcpcs_description": "Destruction of lower or sacral spinal facet joint nerves using imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 22,
            "number_of_medicare_beneficiaries": 12,
            "number_of_distinct_medicare_beneficiary_per_day_services": 22,
            "average_Medicare_allowed_amount": 227.24,
            "average_submitted_charge_amount": 372.18181818,
            "average_medicare_payment_amount": 172.96318182,
            "average_medicare_standardized_amount": 185.63
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "64636",
            "hcpcs_description": "Destruction of lower or sacral spinal facet joint nerves with imaging guidance",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 57,
            "number_of_medicare_beneficiaries": 11,
            "number_of_distinct_medicare_beneficiary_per_day_services": 21,
            "average_Medicare_allowed_amount": 61.062982456,
            "average_submitted_charge_amount": 99.368421053,
            "average_medicare_payment_amount": 47.872807018,
            "average_medicare_standardized_amount": 48.955964912
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "95972",
            "hcpcs_description": "Electronic analysis and programming of implanted complex spinal cord or peripheral neurostimulator generator system during or after surgery, first hour",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 17,
            "number_of_medicare_beneficiaries": 13,
            "number_of_distinct_medicare_beneficiary_per_day_services": 17,
            "average_Medicare_allowed_amount": 41.79,
            "average_submitted_charge_amount": 125,
            "average_medicare_payment_amount": 32.76,
            "average_medicare_standardized_amount": 33.48
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99152",
            "hcpcs_description": "Moderate sedation services by physician also performing a procedure, patient 5 years of age or older, first 15 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 158,
            "number_of_medicare_beneficiaries": 83,
            "number_of_distinct_medicare_beneficiary_per_day_services": 158,
            "average_Medicare_allowed_amount": 12.32,
            "average_submitted_charge_amount": 18,
            "average_medicare_payment_amount": 9.5276582278,
            "average_medicare_standardized_amount": 9.8344303797
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99204",
            "hcpcs_description": "New patient office or other outpatient visit, typically 45 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 73,
            "number_of_medicare_beneficiaries": 73,
            "number_of_distinct_medicare_beneficiary_per_day_services": 73,
            "average_Medicare_allowed_amount": 160.33,
            "average_submitted_charge_amount": 246,
            "average_medicare_payment_amount": 114.66123288,
            "average_medicare_standardized_amount": 121.00123288
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99205",
            "hcpcs_description": "New patient office or other outpatient visit, typically 60 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 36,
            "number_of_medicare_beneficiaries": 36,
            "number_of_distinct_medicare_beneficiary_per_day_services": 36,
            "average_Medicare_allowed_amount": 202.25,
            "average_submitted_charge_amount": 305,
            "average_medicare_payment_amount": 138.30111111,
            "average_medicare_standardized_amount": 153.22555556
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99213",
            "hcpcs_description": "Established patient office or other outpatient visit, typically 15 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 129,
            "number_of_medicare_beneficiaries": 89,
            "number_of_distinct_medicare_beneficiary_per_day_services": 129,
            "average_Medicare_allowed_amount": 70.93,
            "average_submitted_charge_amount": 109,
            "average_medicare_payment_amount": 50.868062016,
            "average_medicare_standardized_amount": 53.268372093
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99214",
            "hcpcs_description": "Established patient office or other outpatient, visit typically 25 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 24,
            "number_of_medicare_beneficiaries": 24,
            "number_of_distinct_medicare_beneficiary_per_day_services": 24,
            "average_Medicare_allowed_amount": 77.84,
            "average_submitted_charge_amount": 115,
            "average_medicare_payment_amount": 58.658333333,
            "average_medicare_standardized_amount": 63.761666667
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99214",
            "hcpcs_description": "Established patient office or other outpatient, visit typically 25 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 330,
            "number_of_medicare_beneficiaries": 140,
            "number_of_distinct_medicare_beneficiary_per_day_services": 330,
            "average_Medicare_allowed_amount": 104.53,
            "average_submitted_charge_amount": 159,
            "average_medicare_payment_amount": 73.218515152,
            "average_medicare_standardized_amount": 78.293848485
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "99215",
            "hcpcs_description": "Established patient office or other outpatient, visit typically 40 minutes",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 49,
            "number_of_medicare_beneficiaries": 43,
            "number_of_distinct_medicare_beneficiary_per_day_services": 49,
            "average_Medicare_allowed_amount": 141.06,
            "average_submitted_charge_amount": 213,
            "average_medicare_payment_amount": 101.48693878,
            "average_medicare_standardized_amount": 107.89653061
        }
    ]
}

provider_1003000134 = {
    "National Provider Identifier": 1003000134,
    "Last Name/Organization Name of the Provider": "CIBULL",
    "First Name of the Provider": "THOMAS",
    "Middle Initial of the Provider": "L",
    "Credentials of the Provider": "M.D.",
    "Gender of the Provider": "M",
    "Entity Type of the Provider": "I",
    "Street Address 1 of the Provider": "2650 RIDGE AVE",
    "Street Address 2 of the Provider": "EVANSTON HOSPITAL",
    "City of the Provider": "EVANSTON",
    "Zip Code of the Provider": "602011718",
    "State Code of the Provider": "IL",
    "Country Code of the Provider": "US",
    "Provider Type": "Pathology",
    "medicaredata": [
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88304",
            "hcpcs_description": "Pathology examination of tissue using a microscope, moderately low complexity",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 268,
            "number_of_medicare_beneficiaries": 249,
            "number_of_distinct_medicare_beneficiary_per_day_services": 252,
            "average_Medicare_allowed_amount": 12.789738806,
            "average_submitted_charge_amount": 115,
            "average_medicare_payment_amount": 9.8421268657,
            "average_medicare_standardized_amount": 9.3908208955
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88305",
            "hcpcs_description": "Pathology examination of tissue using a microscope, intermediate complexity",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 6162,
            "number_of_medicare_beneficiaries": 3481,
            "number_of_distinct_medicare_beneficiary_per_day_services": 4489,
            "average_Medicare_allowed_amount": 41.299941577,
            "average_submitted_charge_amount": 170,
            "average_medicare_payment_amount": 31.426415125,
            "average_medicare_standardized_amount": 30.401900357
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88312",
            "hcpcs_description": "Special stained specimen slides to identify organisms including interpretation and report",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 438,
            "number_of_medicare_beneficiaries": 289,
            "number_of_distinct_medicare_beneficiary_per_day_services": 294,
            "average_Medicare_allowed_amount": 29.240251142,
            "average_submitted_charge_amount": 88,
            "average_medicare_payment_amount": 22.700525114,
            "average_medicare_standardized_amount": 22.163378995
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88313",
            "hcpcs_description": "Special stained specimen slides to examine tissue including interpretation and report",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 86,
            "number_of_medicare_beneficiaries": 63,
            "number_of_distinct_medicare_beneficiary_per_day_services": 65,
            "average_Medicare_allowed_amount": 13.13755814,
            "average_submitted_charge_amount": 68,
            "average_medicare_payment_amount": 10.298139535,
            "average_medicare_standardized_amount": 9.8495348837
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88321",
            "hcpcs_description": "Surgical pathology consultation and report",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 27,
            "number_of_medicare_beneficiaries": 27,
            "number_of_distinct_medicare_beneficiary_per_day_services": 27,
            "average_Medicare_allowed_amount": 92.75,
            "average_submitted_charge_amount": 273.55555556,
            "average_medicare_payment_amount": 67.333333333,
            "average_medicare_standardized_amount": 64.083333333
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88341",
            "hcpcs_description": "Special stained specimen slides to examine tissue",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 385,
            "number_of_medicare_beneficiaries": 117,
            "number_of_distinct_medicare_beneficiary_per_day_services": 118,
            "average_Medicare_allowed_amount": 30.71,
            "average_submitted_charge_amount": 76.083116883,
            "average_medicare_payment_amount": 23.770077922,
            "average_medicare_standardized_amount": 23.170961039
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88342",
            "hcpcs_description": "Tissue or cell analysis by immunologic technique",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 190,
            "number_of_medicare_beneficiaries": 173,
            "number_of_distinct_medicare_beneficiary_per_day_services": 176,
            "average_Medicare_allowed_amount": 38.74,
            "average_submitted_charge_amount": 146.75789474,
            "average_medicare_payment_amount": 29.744473684,
            "average_medicare_standardized_amount": 28.780157895
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88344",
            "hcpcs_description": "Special stained specimen slides to examine tissue",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 413,
            "number_of_medicare_beneficiaries": 304,
            "number_of_distinct_medicare_beneficiary_per_day_services": 326,
            "average_Medicare_allowed_amount": 42.389757869,
            "average_submitted_charge_amount": 124.82082324,
            "average_medicare_payment_amount": 32.531162228,
            "average_medicare_standardized_amount": 31.550677966
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88346",
            "hcpcs_description": "Antibody evaluation",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 84,
            "number_of_medicare_beneficiaries": 83,
            "number_of_distinct_medicare_beneficiary_per_day_services": 83,
            "average_Medicare_allowed_amount": 39.11,
            "average_submitted_charge_amount": 175,
            "average_medicare_payment_amount": 29.345,
            "average_medicare_standardized_amount": 28.841309524
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88360",
            "hcpcs_description": "Microscopic genetic analysis of tumor",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 33,
            "number_of_medicare_beneficiaries": 28,
            "number_of_distinct_medicare_beneficiary_per_day_services": 28,
            "average_Medicare_allowed_amount": 59.21,
            "average_submitted_charge_amount": 182,
            "average_medicare_payment_amount": 45.34969697,
            "average_medicare_standardized_amount": 43.94969697
        },
        {
            "medicare_participation_indicator": "Y",
            "hcpcs_code": "88381",
            "hcpcs_description": "Preparation of specimen, manual",
            "hcpcs_drug_indicator": "N",
            "number_of_services": 24,
            "number_of_medicare_beneficiaries": 17,
            "number_of_distinct_medicare_beneficiary_per_day_services": 18,
            "average_Medicare_allowed_amount": 27.02,
            "average_submitted_charge_amount": 179,
            "average_medicare_payment_amount": 21.189583333,
            "average_medicare_standardized_amount": 20.567083333
        }
    ]
}
