import pytest

provider_1003000126 = {
                "National Provider Identifier": 1003000126,
                "Last Name/Organization Name of the Provider": "ENKESHAFI",
                "First Name of the Provider": "ARDALAN",
                "Middle Initial of the Provider": "",
                "Credentials of the Provider": "M.D.",
                "Gender of the Provider": "M",
                "Entity Type of the Provider": "I",
                "Street Address 1 of the Provider": "900 SETON DR",
                "Street Address 2 of the Provider": "",
                "City of the Provider": "CUMBERLAND",
                "Zip Code of the Provider": "215021854",
                "State Code of the Provider": "MD",
                "Country Code of the Provider": "US",
                "Provider Type": "Internal Medicine",
                "medicaredata": [
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99217",
                    "hcpcs_description": "Hospital observation care discharge",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 100,
                    "number_of_medicare_beneficiaries": 96,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 100,
                    "average_Medicare_allowed_amount": 73.3988,
                    "average_submitted_charge_amount": 325.78,
                    "average_medicare_payment_amount": 56.8272,
                    "average_medicare_standardized_amount": 57.4924
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99218",
                    "hcpcs_description": "Hospital observation care typically 30 minutes",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 26,
                    "number_of_medicare_beneficiaries": 25,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 26,
                    "average_Medicare_allowed_amount": 100.08,
                    "average_submitted_charge_amount": 449,
                    "average_medicare_payment_amount": 78.46,
                    "average_medicare_standardized_amount": 79.306153846
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99219",
                    "hcpcs_description": "Hospital observation care typically 50 minutes",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 52,
                    "number_of_medicare_beneficiaries": 51,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 52,
                    "average_Medicare_allowed_amount": 136.38,
                    "average_submitted_charge_amount": 614,
                    "average_medicare_payment_amount": 102.80769231,
                    "average_medicare_standardized_amount": 103.89538462
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99220",
                    "hcpcs_description": "Hospital observation care typically 70 minutes per day",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 59,
                    "number_of_medicare_beneficiaries": 59,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 59,
                    "average_Medicare_allowed_amount": 190.36372881,
                    "average_submitted_charge_amount": 755.93220339,
                    "average_medicare_payment_amount": 141.29355932,
                    "average_medicare_standardized_amount": 142.86576271
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99221",
                    "hcpcs_description": "Initial hospital inpatient care, typically 30 minutes per day",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 16,
                    "number_of_medicare_beneficiaries": 16,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 16,
                    "average_Medicare_allowed_amount": 101.68,
                    "average_submitted_charge_amount": 462.8125,
                    "average_medicare_payment_amount": 79.71,
                    "average_medicare_standardized_amount": 80.75
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99222",
                    "hcpcs_description": "Initial hospital inpatient care, typically 50 minutes per day",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 59,
                    "number_of_medicare_beneficiaries": 57,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 59,
                    "average_Medicare_allowed_amount": 137.31,
                    "average_submitted_charge_amount": 625,
                    "average_medicare_payment_amount": 105.82542373,
                    "average_medicare_standardized_amount": 107.07067797
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99223",
                    "hcpcs_description": "Initial hospital inpatient care, typically 70 minutes per day",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 114,
                    "number_of_medicare_beneficiaries": 110,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 114,
                    "average_Medicare_allowed_amount": 206.06157895,
                    "average_submitted_charge_amount": 923.99122807,
                    "average_medicare_payment_amount": 160.37719298,
                    "average_medicare_standardized_amount": 160.02631579
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99232",
                    "hcpcs_description": "Subsequent hospital inpatient care, typically 25 minutes per day",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 627,
                    "number_of_medicare_beneficiaries": 233,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 627,
                    "average_Medicare_allowed_amount": 72.62245614,
                    "average_submitted_charge_amount": 326.24561404,
                    "average_medicare_payment_amount": 56.366730463,
                    "average_medicare_standardized_amount": 57.047894737
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99233",
                    "hcpcs_description": "Subsequent hospital inpatient care, typically 35 minutes per day",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 207,
                    "number_of_medicare_beneficiaries": 127,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 207,
                    "average_Medicare_allowed_amount": 106.65391304,
                    "average_submitted_charge_amount": 461.07246377,
                    "average_medicare_payment_amount": 82.820676329,
                    "average_medicare_standardized_amount": 83.196038647
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99239",
                    "hcpcs_description": "Hospital discharge day management, more than 30 minutes",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 341,
                    "number_of_medicare_beneficiaries": 291,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 341,
                    "average_Medicare_allowed_amount": 108.36328446,
                    "average_submitted_charge_amount": 481.68621701,
                    "average_medicare_payment_amount": 84.056158358,
                    "average_medicare_standardized_amount": 84.955131965
                },
                {
                    "medicare_participation_indicator": "Y",
                    "hcpcs_code": "99291",
                    "hcpcs_description": "Critical care delivery critically ill or injured patient, first 30-74 minutes",
                    "hcpcs_drug_indicator": "N",
                    "number_of_services": 36,
                    "number_of_medicare_beneficiaries": 23,
                    "number_of_distinct_medicare_beneficiary_per_day_services": 36,
                    "average_Medicare_allowed_amount": 224.17,
                    "average_submitted_charge_amount": 1400,
                    "average_medicare_payment_amount": 175.75,
                    "average_medicare_standardized_amount": 177.65666667
                }
                ]
            }
