import pytest

provider_1003000126 = {
                    "National Provider Identifier": 1003000126,
                    "Last Name/Organization Name of the Provider": "ENKESHAFI",
                    "First Name of the Provider": "ARDALAN",
                    "Middle Initial of the Provider": "",
                    "Credentials of the Provider": "M.D.",
                    "Gender of the Provider": "M",
                    "Entity Type of the Provider": "I",
                    "Street Address 1 of the Provider": "900 SETON DR",
                    "Street Address 2 of the Provider": "",
                    "City of the Provider": "CUMBERLAND",
                    "Zip Code of the Provider": "215021854",
                    "State Code of the Provider": "MD",
                    "Country Code of the Provider": "US",
                    "Provider Type": "Internal Medicine",
                    "medicaredata": [
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99217",
                        "Hcpcs Description": "Hospital observation care discharge",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 100,
                        "Number of Medicare Beneficiaries": 96,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 100,
                        "Average Medicare Allowed Amount": 73.3988,
                        "Average Medicare Submitted Charge Amount": 325.78,
                        "Average Medicare Payment Amount": 56.8272,
                        "Average Medicare Standardized Amount": 57.4924
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99218",
                        "Hcpcs Description": "Hospital observation care typically 30 minutes",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 26,
                        "Number of Medicare Beneficiaries": 25,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 26,
                        "Average Medicare Allowed Amount": 100.08,
                        "Average Medicare Submitted Charge Amount": 449,
                        "Average Medicare Payment Amount": 78.46,
                        "Average Medicare Standardized Amount": 79.306153846
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99219",
                        "Hcpcs Description": "Hospital observation care typically 50 minutes",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 52,
                        "Number of Medicare Beneficiaries": 51,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 52,
                        "Average Medicare Allowed Amount": 136.38,
                        "Average Medicare Submitted Charge Amount": 614,
                        "Average Medicare Payment Amount": 102.80769231,
                        "Average Medicare Standardized Amount": 103.89538462
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99220",
                        "Hcpcs Description": "Hospital observation care typically 70 minutes per day",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 59,
                        "Number of Medicare Beneficiaries": 59,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 59,
                        "Average Medicare Allowed Amount": 190.36372881,
                        "Average Medicare Submitted Charge Amount": 755.93220339,
                        "Average Medicare Payment Amount": 141.29355932,
                        "Average Medicare Standardized Amount": 142.86576271
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99221",
                        "Hcpcs Description": "Initial hospital inpatient care, typically 30 minutes per day",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 16,
                        "Number of Medicare Beneficiaries": 16,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 16,
                        "Average Medicare Allowed Amount": 101.68,
                        "Average Medicare Submitted Charge Amount": 462.8125,
                        "Average Medicare Payment Amount": 79.71,
                        "Average Medicare Standardized Amount": 80.75
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99222",
                        "Hcpcs Description": "Initial hospital inpatient care, typically 50 minutes per day",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 59,
                        "Number of Medicare Beneficiaries": 57,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 59,
                        "Average Medicare Allowed Amount": 137.31,
                        "Average Medicare Submitted Charge Amount": 625,
                        "Average Medicare Payment Amount": 105.82542373,
                        "Average Medicare Standardized Amount": 107.07067797
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99223",
                        "Hcpcs Description": "Initial hospital inpatient care, typically 70 minutes per day",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 114,
                        "Number of Medicare Beneficiaries": 110,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 114,
                        "Average Medicare Allowed Amount": 206.06157895,
                        "Average Medicare Submitted Charge Amount": 923.99122807,
                        "Average Medicare Payment Amount": 160.37719298,
                        "Average Medicare Standardized Amount": 160.02631579
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99232",
                        "Hcpcs Description": "Subsequent hospital inpatient care, typically 25 minutes per day",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 627,
                        "Number of Medicare Beneficiaries": 233,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 627,
                        "Average Medicare Allowed Amount": 72.62245614,
                        "Average Medicare Submitted Charge Amount": 326.24561404,
                        "Average Medicare Payment Amount": 56.366730463,
                        "Average Medicare Standardized Amount": 57.047894737
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99233",
                        "Hcpcs Description": "Subsequent hospital inpatient care, typically 35 minutes per day",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 207,
                        "Number of Medicare Beneficiaries": 127,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 207,
                        "Average Medicare Allowed Amount": 106.65391304,
                        "Average Medicare Submitted Charge Amount": 461.07246377,
                        "Average Medicare Payment Amount": 82.820676329,
                        "Average Medicare Standardized Amount": 83.196038647
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99239",
                        "Hcpcs Description": "Hospital discharge day management, more than 30 minutes",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 341,
                        "Number of Medicare Beneficiaries": 291,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 341,
                        "Average Medicare Allowed Amount": 108.36328446,
                        "Average Medicare Submitted Charge Amount": 481.68621701,
                        "Average Medicare Payment Amount": 84.056158358,
                        "Average Medicare Standardized Amount": 84.955131965
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "99291",
                        "Hcpcs Description": "Critical care delivery critically ill or injured patient, first 30-74 minutes",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 36,
                        "Number of Medicare Beneficiaries": 23,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 36,
                        "Average Medicare Allowed Amount": 224.17,
                        "Average Medicare Submitted Charge Amount": 1400,
                        "Average Medicare Payment Amount": 175.75,
                        "Average Medicare Standardized Amount": 177.65666667
                        }
                    ]
                    }

provider_1003000407 = {
                        "National Provider Identifier": 1003000407,
                        "Last Name/Organization Name of the Provider": "GIRARDI",
                        "First Name of the Provider": "DAVID",
                        "Middle Initial of the Provider": "J",
                        "Credentials of the Provider": "D.O.",
                        "Gender of the Provider": "M",
                        "Entity Type of the Provider": "I",
                        "Street Address 1 of the Provider": "100 HOSPITAL RD",
                        "Street Address 2 of the Provider": "",
                        "City of the Provider": "BROOKVILLE",
                        "Zip Code of the Provider": "158251367",
                        "State Code of the Provider": "PA",
                        "Country Code of the Provider": "US",
                        "Provider Type": "Family Practice",
                        "medicaredata": [
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99217",
                            "Hcpcs Description": "Hospital observation care discharge",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 15,
                            "Number of Medicare Beneficiaries": 15,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 15,
                            "Average Medicare Allowed Amount": 72.3,
                            "Average Medicare Submitted Charge Amount": 102.33333333,
                            "Average Medicare Payment Amount": 54.42,
                            "Average Medicare Standardized Amount": 57.96
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99219",
                            "Hcpcs Description": "Hospital observation care typically 50 minutes",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 27,
                            "Number of Medicare Beneficiaries": 26,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 27,
                            "Average Medicare Allowed Amount": 135.33,
                            "Average Medicare Submitted Charge Amount": 170,
                            "Average Medicare Payment Amount": 101.85,
                            "Average Medicare Standardized Amount": 107.81074074
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99220",
                            "Hcpcs Description": "Hospital observation care typically 70 minutes per day",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 34,
                            "Number of Medicare Beneficiaries": 34,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 34,
                            "Average Medicare Allowed Amount": 185.02,
                            "Average Medicare Submitted Charge Amount": 213.67647059,
                            "Average Medicare Payment Amount": 139.26,
                            "Average Medicare Standardized Amount": 147.72
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99221",
                            "Hcpcs Description": "Initial hospital inpatient care, typically 30 minutes per day",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 19,
                            "Number of Medicare Beneficiaries": 19,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 19,
                            "Average Medicare Allowed Amount": 101.24,
                            "Average Medicare Submitted Charge Amount": 125,
                            "Average Medicare Payment Amount": 73.383157895,
                            "Average Medicare Standardized Amount": 81.812631579
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99222",
                            "Hcpcs Description": "Initial hospital inpatient care, typically 50 minutes per day",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 39,
                            "Number of Medicare Beneficiaries": 37,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 39,
                            "Average Medicare Allowed Amount": 136.44,
                            "Average Medicare Submitted Charge Amount": 166.92307692,
                            "Average Medicare Payment Amount": 100.04717949,
                            "Average Medicare Standardized Amount": 106.00025641
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99223",
                            "Hcpcs Description": "Initial hospital inpatient care, typically 70 minutes per day",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 74,
                            "Number of Medicare Beneficiaries": 73,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 74,
                            "Average Medicare Allowed Amount": 200.545,
                            "Average Medicare Submitted Charge Amount": 243.39189189,
                            "Average Medicare Payment Amount": 149.435,
                            "Average Medicare Standardized Amount": 161.39081081
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99226",
                            "Hcpcs Description": "Subsequent observation care, typically 35 minutes per day",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 17,
                            "Number of Medicare Beneficiaries": 13,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 17,
                            "Average Medicare Allowed Amount": 100.36705882,
                            "Average Medicare Submitted Charge Amount": 131.17647059,
                            "Average Medicare Payment Amount": 75.539411765,
                            "Average Medicare Standardized Amount": 83.570588235
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99231",
                            "Hcpcs Description": "Subsequent hospital inpatient care, typically 15 minutes per day",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 74,
                            "Number of Medicare Beneficiaries": 48,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 74,
                            "Average Medicare Allowed Amount": 39.16,
                            "Average Medicare Submitted Charge Amount": 90,
                            "Average Medicare Payment Amount": 27.841081081,
                            "Average Medicare Standardized Amount": 30.649459459000003
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99232",
                            "Hcpcs Description": "Subsequent hospital inpatient care, typically 25 minutes per day",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 241,
                            "Number of Medicare Beneficiaries": 122,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 241,
                            "Average Medicare Allowed Amount": 71.9,
                            "Average Medicare Submitted Charge Amount": 150,
                            "Average Medicare Payment Amount": 53.631327801000005,
                            "Average Medicare Standardized Amount": 57.323858921
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99233",
                            "Hcpcs Description": "Subsequent hospital inpatient care, typically 35 minutes per day",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 76,
                            "Number of Medicare Beneficiaries": 48,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 76,
                            "Average Medicare Allowed Amount": 103.97,
                            "Average Medicare Submitted Charge Amount": 175,
                            "Average Medicare Payment Amount": 78.25,
                            "Average Medicare Standardized Amount": 82.884736842
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99239",
                            "Hcpcs Description": "Hospital discharge day management, more than 30 minutes",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 129,
                            "Number of Medicare Beneficiaries": 123,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 129,
                            "Average Medicare Allowed Amount": 106.69,
                            "Average Medicare Submitted Charge Amount": 135.94573643,
                            "Average Medicare Payment Amount": 79.241860465,
                            "Average Medicare Standardized Amount": 84.97968992199999
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99306",
                            "Hcpcs Description": "Initial nursing facility visit, typically 45 minutes per day",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 11,
                            "Number of Medicare Beneficiaries": 11,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 11,
                            "Average Medicare Allowed Amount": 165.59,
                            "Average Medicare Submitted Charge Amount": 185,
                            "Average Medicare Payment Amount": 124.63,
                            "Average Medicare Standardized Amount": 124.63
                            },
                            {
                            "Medicare Participation Indicator": "Y",
                            "Hcpcs code": "99316",
                            "Hcpcs Description": "Nursing facility discharge management, more than 30 minutes",
                            "Hcpcs Drug Indicator": "N",
                            "Number of Services": 39,
                            "Number of Medicare Beneficiaries": 38,
                            "Number of Distinct Medicare Beneficiary Per Day Service": 39,
                            "Average Medicare Allowed Amount": 105.05,
                            "Average Medicare Submitted Charge Amount": 120,
                            "Average Medicare Payment Amount": 79.07,
                            "Average Medicare Standardized Amount": 84.13
                            }
                        ]
                        }


provider_1003000134 = {
                    "National Provider Identifier": 1003000134,
                    "Last Name/Organization Name of the Provider": "CIBULL",
                    "First Name of the Provider": "THOMAS",
                    "Middle Initial of the Provider": "L",
                    "Credentials of the Provider": "M.D.",
                    "Gender of the Provider": "M",
                    "Entity Type of the Provider": "I",
                    "Street Address 1 of the Provider": "2650 RIDGE AVE",
                    "Street Address 2 of the Provider": "EVANSTON HOSPITAL",
                    "City of the Provider": "EVANSTON",
                    "Zip Code of the Provider": "602011718",
                    "State Code of the Provider": "IL",
                    "Country Code of the Provider": "US",
                    "Provider Type": "Pathology",
                    "medicaredata": [
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88304",
                        "Hcpcs Description": "Pathology examination of tissue using a microscope, moderately low complexity",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 268,
                        "Number of Medicare Beneficiaries": 249,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 252,
                        "Average Medicare Allowed Amount": 12.789738805999999,
                        "Average Medicare Submitted Charge Amount": 115,
                        "Average Medicare Payment Amount": 9.842126865700001,
                        "Average Medicare Standardized Amount": 9.3908208955
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88305",
                        "Hcpcs Description": "Pathology examination of tissue using a microscope, intermediate complexity",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 6162,
                        "Number of Medicare Beneficiaries": 3481,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 4489,
                        "Average Medicare Allowed Amount": 41.299941577,
                        "Average Medicare Submitted Charge Amount": 170,
                        "Average Medicare Payment Amount": 31.426415125,
                        "Average Medicare Standardized Amount": 30.401900357
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88312",
                        "Hcpcs Description": "Special stained specimen slides to identify organisms including interpretation and report",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 438,
                        "Number of Medicare Beneficiaries": 289,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 294,
                        "Average Medicare Allowed Amount": 29.240251141999998,
                        "Average Medicare Submitted Charge Amount": 88,
                        "Average Medicare Payment Amount": 22.700525114,
                        "Average Medicare Standardized Amount": 22.163378995
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88313",
                        "Hcpcs Description": "Special stained specimen slides to examine tissue including interpretation and report",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 86,
                        "Number of Medicare Beneficiaries": 63,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 65,
                        "Average Medicare Allowed Amount": 13.13755814,
                        "Average Medicare Submitted Charge Amount": 68,
                        "Average Medicare Payment Amount": 10.298139535,
                        "Average Medicare Standardized Amount": 9.8495348837
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88321",
                        "Hcpcs Description": "Surgical pathology consultation and report",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 27,
                        "Number of Medicare Beneficiaries": 27,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 27,
                        "Average Medicare Allowed Amount": 92.75,
                        "Average Medicare Submitted Charge Amount": 273.55555556,
                        "Average Medicare Payment Amount": 67.333333333,
                        "Average Medicare Standardized Amount": 64.083333333
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88341",
                        "Hcpcs Description": "Special stained specimen slides to examine tissue",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 385,
                        "Number of Medicare Beneficiaries": 117,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 118,
                        "Average Medicare Allowed Amount": 30.71,
                        "Average Medicare Submitted Charge Amount": 76.083116883,
                        "Average Medicare Payment Amount": 23.770077922,
                        "Average Medicare Standardized Amount": 23.170961039
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88342",
                        "Hcpcs Description": "Tissue or cell analysis by immunologic technique",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 190,
                        "Number of Medicare Beneficiaries": 173,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 176,
                        "Average Medicare Allowed Amount": 38.74,
                        "Average Medicare Submitted Charge Amount": 146.75789474,
                        "Average Medicare Payment Amount": 29.744473684000003,
                        "Average Medicare Standardized Amount": 28.780157895
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88344",
                        "Hcpcs Description": "Special stained specimen slides to examine tissue",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 413,
                        "Number of Medicare Beneficiaries": 304,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 326,
                        "Average Medicare Allowed Amount": 42.389757869,
                        "Average Medicare Submitted Charge Amount": 124.82082324,
                        "Average Medicare Payment Amount": 32.531162228,
                        "Average Medicare Standardized Amount": 31.550677966
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88346",
                        "Hcpcs Description": "Antibody evaluation",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 84,
                        "Number of Medicare Beneficiaries": 83,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 83,
                        "Average Medicare Allowed Amount": 39.11,
                        "Average Medicare Submitted Charge Amount": 175,
                        "Average Medicare Payment Amount": 29.345,
                        "Average Medicare Standardized Amount": 28.841309524
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88360",
                        "Hcpcs Description": "Microscopic genetic analysis of tumor",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 33,
                        "Number of Medicare Beneficiaries": 28,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 28,
                        "Average Medicare Allowed Amount": 59.21,
                        "Average Medicare Submitted Charge Amount": 182,
                        "Average Medicare Payment Amount": 45.34969697,
                        "Average Medicare Standardized Amount": 43.94969697
                        },
                        {
                        "Medicare Participation Indicator": "Y",
                        "Hcpcs code": "88381",
                        "Hcpcs Description": "Preparation of specimen, manual",
                        "Hcpcs Drug Indicator": "N",
                        "Number of Services": 24,
                        "Number of Medicare Beneficiaries": 17,
                        "Number of Distinct Medicare Beneficiary Per Day Service": 18,
                        "Average Medicare Allowed Amount": 27.02,
                        "Average Medicare Submitted Charge Amount": 179,
                        "Average Medicare Payment Amount": 21.189583332999998,
                        "Average Medicare Standardized Amount": 20.567083333
                        }
                    ]
                    }